version: '3'

services:
  example:
    container_name: example
    image: postchain:latest
    volumes:
      - ./rell:/usr/src/rell
      - ./data:/var/lib/postgresql/data
    ports:
      - 7740:7740
