image: atlassian/default-image:2

definitions:
  steps:
    - step: &ci
        name: "Continuous Integration"
        script:
          - ./download-binaries.sh
          - docker build -t postchain .
          - cd example
          - docker-compose up -d
          - sleep 10
          - curl http://localhost:7740/brid/iid_0
        caches:
          - docker
        services:
          - docker

    - step: &publish
        name: "Publish image"
        script:
          - ./download-binaries.sh
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN
          - IMAGE=snieking/postchain
          - docker build -t $IMAGE:latest .
          - docker tag $IMAGE:latest $IMAGE:$BITBUCKET_TAG
          - docker push snieking/postchain:$BITBUCKET_TAG
          - docker push snieking/postchain:latest
        services:
          - docker
pipelines:
  default:
    - step: *ci

  tags:
    '*':
      - step: *ci
      - step: *publish