version: '3.3'

services:
  example:
    container_name: example
    image: snieking/postchain
    volumes:
      - ./rell:/usr/src/rell
      - ./data:/var/lib/postgresql/data
    ports:
      - 7740:80
