# This is a basic workflow to help you get started with Actions

name: Continuous Delivery

# Controls when the workflow will run
on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: snieking
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build and push Docker images
        run: |
          ./download-binaries.sh
          IMAGE=snieking/postchain
          docker build -t $IMAGE:latest .
          docker tag $IMAGE:latest $IMAGE:$VERSION
          docker push $IMAGE:$VERSION
          docker push $IMAGE:latest
          
