# This is a basic workflow to help you get started with Actions

name: Continuous Delivery

# Controls when the workflow will run
on:
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "IMAGE=snieking/postchain" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: snieking
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build and push Docker images
        id: publish
        run: |
          ./download-binaries.sh
          docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag $IMAGE:latest .
          docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag $IMAGE:$VERSION .
