# This is a basic workflow to help you get started with Actions

name: Continuous Integration

# Controls when the workflow will run
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          echo "IMAGE=snieking/postchain" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        run: |
          ./download-binaries.sh
          docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag $IMAGE:latest .

      - name: List images
        run: docker images

      - name: Test single node
        run: |
          docker-compose up -d
          sleep 30s
          curl http://localhost:7740/brid/iid_0
          docker-compose down
        working-directory: examples/single-node

      - name: Test multi node
        run: |
          docker-compose up -d
          sleep 30s
          curl http://localhost:7741/brid/iid_0
          docker-compose down
        working-directory: examples/multi-node
