# This is a basic workflow to help you get started with Actions

name: Continuous Integration

# Controls when the workflow will run
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          ./download-binaries.sh
          docker build -t postchain .

      - name: Test single node
        working-directory: examples/single-node
        run: |
          docker-compose up -d
          sleep 30s
          docker logs example
          curl http://localhost:7740/brid/iid_0
          docker-compose down

      - name: Test multi node
        working-directory: examples/multi-node
        run: |
          docker-compose up -d
          sleep 30s
          docker logs bc0
          docker logs bc1
          curl http://localhost:7741/brid/iid_0
          docker-compose down

      - name: Test external db
        working-directory: examples/external-db
        run: |
          docker-compose up -d
          sleep 30s
          docker logs example
          curl http://localhost:7740/brid/iid_0
          docker-compose down
